"""Run-aware CLI, evidence and compare-and-restore recovery for goalrun.

The engine's path bindings and SESSION exist only in one CLI process. Durable
state lives in Store, independently of the installed script or agent host.
"""
import argparse
import base64
from contextlib import contextmanager, redirect_stderr, redirect_stdout
import hashlib
import json
import os
import re
from pathlib import Path
import shutil
import shlex
import stat
import sysconfig
import subprocess
import sys
import time
import uuid

from run_store import RunError, Store

ACTIONS = ('init', 'list', 'inspect', 'resume', 'checkpoint', 'release', 'migrate')


def digest(data):
    return hashlib.sha256(data).hexdigest()


def atomic_json(store, path, data):
    store._safe(path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    store._atomic(path, data)


@contextmanager
def workspace_lock(engine):
    store = Store()
    store._safe(os.path.join(store.root, '.testcases', 'goalrun.lock'))
    lock = engine.hold_lock()
    try:
        yield lock
    finally:
        engine.drop_lock(lock)


def directory_contents(target, engine, seen):
    """Every file under a directory that is itself an input, not a workspace root."""
    contents = {}
    for base, dirs, names in os.walk(target):
        dirs[:] = [d for d in dirs if d not in engine.BASELINE_SKIP - {'bin', 'obj', 'target', 'dist', 'build'}]
        for name in names + dirs:
            full = os.path.join(base, name)
            contents[os.path.relpath(full, target)] = input_mark(full, engine, seen)
    return contents


def input_mark(path, engine, seen=frozenset()):
    """Track link identity and the input it reads, including directory links and cycles."""
    if not os.path.lexists(path):
        return ['absent', None]
    metadata = os.lstat(path)
    mode = metadata.st_mode & 0o7777
    if not (stat.S_ISREG(metadata.st_mode) or stat.S_ISLNK(metadata.st_mode)):
        return ['type:' + str(stat.S_IFMT(metadata.st_mode)), mode, metadata.st_rdev]
    mark = engine._mark(path)
    if not os.path.islink(path):
        return [mark, mode]
    target = os.path.realpath(path)
    if target in seen:
        return [mark, 'cycle']
    if os.path.isfile(target):
        return [mark, input_mark(target, engine, seen)]
    if not os.path.isdir(target):
        return [mark, 'unavailable']
    return [mark, os.stat(target).st_mode & 0o7777, directory_contents(target, engine, seen | {target})]


def redacted_argv(argv, token):
    return [arg.replace(token, '[redacted]') if token else arg for arg in argv]


def runtime_mark(store, view, engine):
    # Persist only the resulting digest, never environment values or credentials.
    environment = {k: v for k, v in os.environ.items()
                   if k not in {'_', 'SHLVL', 'PWD', 'OLDPWD', 'TERM', 'COLUMNS', 'LINES'}}
    tools = {sys.executable: input_mark(sys.executable, engine)}
    ledger = Path(view['paths']['goalrun_dir']) / 'ledger.tsv'
    if ledger.is_file():
        for line in ledger.read_text().splitlines():
            cells = line.split('\t')
            if len(cells) < 3 or line.startswith('#'):
                continue
            try:
                words = shlex.split(cells[2], posix=True)
            except ValueError:
                words = []
            for word in words:
                executable = shutil.which(word)
                if executable and os.path.isfile(executable):
                    tools[executable] = input_mark(executable, engine)
    # Installed packages are excluded from the source walk, but changes to their
    # file identities still affect proof. Ignore generated bytecode/cache files.
    dependencies = {}
    roots = {sysconfig.get_path('purelib'), sysconfig.get_path('platlib'),
             os.path.join(store.root, 'node_modules'), os.path.join(store.root, '.venv'),
             os.environ.get('VIRTUAL_ENV')}
    roots.update(p for p in os.environ.get('PYTHONPATH', '').split(os.pathsep) if p)
    for root in sorted(p for p in roots if p and os.path.isdir(p)):
        seen = set()
        for base, dirs, names in os.walk(root, followlinks=True):
            real = os.path.realpath(base)
            if real in seen:
                dirs[:] = []
                continue
            seen.add(real)
            dirs[:] = [d for d in dirs if d not in {'__pycache__', '.cache', '.git', '.testcases',
                                                   '.pytest_cache', '.ruff_cache', '.mypy_cache'}]
            dependencies[base] = ['directory', os.stat(base).st_mode & 0o7777, real]
            for name in names:
                if name.endswith(('.pyc', '.pyo')):
                    continue
                path = os.path.join(base, name)
                try:
                    info = os.lstat(path)
                except FileNotFoundError:
                    continue
                dependencies[path] = [info.st_mode, info.st_size, info.st_mtime_ns,
                                      info.st_ctime_ns, info.st_ino,
                                      os.readlink(path) if stat.S_ISLNK(info.st_mode) else None]
    return digest(json.dumps([sys.version, environment, tools, dependencies], sort_keys=True).encode())


def tracked_paths(root):
    """Tracked inputs override generated-directory guesses, except private run state."""
    try:
        result = subprocess.run(['git', '-C', os.path.abspath(root), 'ls-files', '-z'],
                                capture_output=True, timeout=10)
    except FileNotFoundError:
        return []
    if result.returncode:
        if os.path.lexists(os.path.join(root, '.git')):
            raise RunError('cannot enumerate tracked inputs; restore the Git index before verifying')
        return []
    return [p for p in os.fsdecode(result.stdout).split('\0') if p and
            p.split('/')[0] not in {'.git', '.testcases'}]


def source_paths(root, engine):
    """Walk ordinary inputs, including ignored files and empty directories.

    Ignore rules identify common generated-output directories, not arbitrary
    input files. Tracked paths override output/cache exclusions; private run and
    Git state never participate.
    """
    root = os.path.abspath(root)
    tracked = set(tracked_paths(root))
    caches = engine.BASELINE_SKIP - {'bin', 'obj', 'target', 'dist', 'build'}
    private = {'.git', '.testcases'}
    ancestors = {str(parent) for path in tracked for parent in Path(path).parents}
    outputs = {}

    def excluded(relative, directory=False):
        parts = Path(relative).parts
        if any(part in private for part in parts):
            return True
        if relative in tracked or (directory and relative in ancestors):
            return False
        if any(part in caches for part in parts) or parts[-1] in {'coverage.xml', 'junit.xml'} or \
                parts[-1] == '.coverage' or parts[-1].startswith('.coverage.'):
            return True
        for index, part in enumerate(parts if directory else parts[:-1]):
            if part not in {'bin', 'obj', 'target', 'dist', 'build'}:
                continue
            prefix = str(Path(*parts[:index + 1]))
            if prefix not in outputs:
                try:
                    result = subprocess.run(['git', '-C', root, 'check-ignore', '--no-index', '-q', prefix + '/'],
                                            capture_output=True, timeout=10)
                except FileNotFoundError:
                    outputs[prefix] = False
                else:
                    outputs[prefix] = result.returncode == 0
            if outputs[prefix]:
                return True
        return False

    paths = set(tracked)
    for base, dirs, names in os.walk(root):
        descend = []
        for name in dirs:
            full = os.path.join(base, name)
            relative = os.path.relpath(full, root)
            if excluded(relative, directory=True):
                continue
            paths.add(relative)
            # Repository roots recurse in source_entries, retaining their own
            # tracked overrides and generated-output policy.
            if not os.path.lexists(os.path.join(full, '.git')):
                descend.append(name)
        dirs[:] = descend
        for name in names:
            relative = os.path.relpath(os.path.join(base, name), root)
            if not excluded(relative):
                paths.add(relative)
    return sorted(paths)


def source_entries(root, engine, seen=frozenset()):
    """Expand nested repositories using the same selection as their worktrees."""
    real = os.path.realpath(root)
    if real in seen:
        return
    for relative in source_paths(root, engine):
        full = os.path.join(root, relative)
        directory = os.path.isdir(full) and not os.path.islink(full)
        yield relative, full, directory
        if directory and os.path.lexists(os.path.join(full, '.git')):
            for child, path, child_directory in source_entries(full, engine, seen | {real}):
                yield os.path.join(relative, child), path, child_directory


def source_exclusions(root, engine):
    """Snapshot omitted paths at initialization without reading generated file contents.

    Omitted directories are boundaries: do not traverse dependency/output trees.
    Selected parents containing tracked overrides still expose omitted siblings.
    """
    selected = {os.path.normpath(relative) for relative, _, _ in source_entries(root, engine)}
    excluded = []
    for base, dirs, names in os.walk(root):
        descend = []
        for name in dirs:
            relative = os.path.normpath(os.path.relpath(os.path.join(base, name), root))
            if relative not in selected:
                excluded.append(relative)
            else:
                descend.append(name)
        dirs[:] = descend
        for name in names:
            relative = os.path.normpath(os.path.relpath(os.path.join(base, name), root))
            if relative not in selected:
                excluded.append(relative)
    return sorted(excluded)


def git_index(root):
    """Semantic staged entries and persistent flags, independent of stat-cache refresh."""
    try:
        result = subprocess.run(['git', '-C', os.path.abspath(root), 'ls-files',
                                 '--stage', '--debug', '-z'], capture_output=True, timeout=10)
    except FileNotFoundError:
        return None
    if result.returncode:
        if os.path.lexists(os.path.join(root, '.git')):
            raise RunError('cannot read staged inputs; restore the Git index before verifying')
        return None
    # --debug follows each NUL-terminated pathname with stat-cache fields and
    # flags. Preserve mode/object/stage and assume-unchanged, skip-worktree,
    # intent-to-add; ctime, mtime, inode and fsmonitor cache flags are volatile.
    pattern = rb'([0-9]{6}) ([0-9a-f]+) ([0-3])\t([^\0]*)\0' \
              rb'  ctime: [^\n]*\n  mtime: [^\n]*\n  dev: [^\n]*\n' \
              rb'  uid: [^\n]*\n  size: [^\n]*\tflags: ([0-9a-f]+)\n'
    entries = []
    offset = 0
    for match in re.finditer(pattern, result.stdout):
        if match.start() != offset:
            raise RunError('cannot parse staged inputs; restore the Git index before verifying')
        mode, object_id, stage, path, flags = match.groups()
        entries.append([os.fsdecode(path), mode.decode(), object_id.decode(), int(stage),
                        int(flags, 16) & (0x8000 | 0x40000000 | 0x20000000)])
        offset = match.end()
    if offset != len(result.stdout):
        raise RunError('cannot parse staged inputs; restore the Git index before verifying')
    return entries


def git_head(root):
    try:
        result = subprocess.run(['git', '-C', os.path.abspath(root), 'rev-parse', '--verify', 'HEAD'],
                                capture_output=True, timeout=10)
    except FileNotFoundError:
        return None
    return result.stdout.decode().strip() if result.returncode == 0 else None


def git_symbolic_branch(root):
    """The branch HEAD is on, which the resolved commit alone cannot tell: two branches
    can point at one commit, and a check that reads the branch name must not keep a
    proof taken on the other one. Detached or absent: None."""
    try:
        result = subprocess.run(['git', '-C', os.path.abspath(root), 'symbolic-ref',
                                 '--quiet', '--short', 'HEAD'], capture_output=True, timeout=10)
    except FileNotFoundError:
        return None
    return result.stdout.decode().strip() if result.returncode == 0 else None


def fingerprint(store, view, engine):
    # Synthetic metadata and workspace paths have separate collision-free namespaces.
    metadata = {'runtime': runtime_mark(store, view, engine),
                'workspace-mode': os.stat(store.root).st_mode & 0o7777}
    for label, path in (('engine', engine.__file__), ('cli', __file__),
                        ('store', sys.modules[Store.__module__].__file__)):
        metadata[label] = engine._mark(path)
    files = {}
    metadata['git-heads'] = {'': git_head(store.root)}
    metadata['git-indexes'] = {'': git_index(store.root)}
    metadata['git-branches'] = {'': git_symbolic_branch(store.root)}
    for relative, full, directory in source_entries(store.root, engine):
        if directory and os.path.lexists(os.path.join(full, '.git')):
            metadata['git-heads'][relative] = git_head(full)
            metadata['git-indexes'][relative] = git_index(full)
            metadata['git-branches'][relative] = git_symbolic_branch(full)
        files[relative] = input_mark(full, engine)
        parent = os.path.dirname(full)
        while parent != store.root:
            files[os.path.relpath(parent, store.root)] = input_mark(parent, engine)
            parent = os.path.dirname(parent)
    inputs = {}
    for name in ('reqs.txt', 'ledger.tsv', 'baseline.json', 'signoff.tsv', engine.WAIVER_BINDINGS):
        full = store._safe(os.path.join(view['paths']['goalrun_dir'], name))
        inputs[name] = engine._mark(full) if os.path.exists(full) else 'absent'
    # Local spec paths outside the workspace are read-only inputs too.
    spec = view['manifest']['spec']
    spec_mark = None
    if spec:
        full = spec if os.path.isabs(spec) else os.path.join(store.root, spec)
        if os.path.isdir(full) and not os.path.islink(full):
            # An ordinary spec directory is the requirements inside it: recurse as
            # linked directories already do, so edits, additions and removals beneath
            # it change the fingerprint instead of leaving a stale proof current.
            target = os.path.realpath(full)
            spec_mark = [engine._mark(full), os.stat(target).st_mode & 0o7777,
                         directory_contents(target, engine, frozenset({target}))]
        else:
            spec_mark = input_mark(full, engine)
    return digest(json.dumps({'metadata': metadata, 'workspace': files,
                              'run-inputs': inputs, 'spec': [spec, spec_mark]}, sort_keys=True).encode())


def latest_proof(checkpoint):
    proof = checkpoint.get('last_proof')
    if proof is None:
        previous = checkpoint.get('last_evidence')
        if previous and previous.get('whole_ledger_verified'):
            proof = previous
    return proof


def evidence_view(store, view, engine):
    checkpoint = view['checkpoint']
    evidence = checkpoint.get('last_evidence')
    proof = latest_proof(checkpoint)
    current = fingerprint(store, view, engine)

    def public(record):
        if record is None:
            return None
        result = dict(record)
        result['argv'] = redacted_argv(result.get('argv', []), checkpoint.get('token'))
        return result

    def stale(record):
        return (record is None or bool(record.get('invalidated_by')) or
                record.get('ownership_epoch') != checkpoint['ownership_epoch'] or
                record.get('fingerprint') != current)

    view['last_evidence'] = public(evidence)
    view['evidence_stale'] = stale(evidence)
    view['last_proof'] = public(proof)
    view['proof_stale'] = stale(proof)
    # Inspection/listing cannot confer writer privileges.
    view['checkpoint'] = dict(checkpoint)
    view['checkpoint'].pop('token', None)
    if evidence is not None:
        view['checkpoint']['last_evidence'] = view['last_evidence']
    if proof is not None:
        view['checkpoint']['last_proof'] = view['last_proof']
    return view


def journal_path(store, run_id, row_id):
    # Row IDs aren't filenames: existing ledger IDs can contain punctuation/slashes.
    return store._safe(os.path.join(store._paths(run_id)['goalrun_dir'], 'undo',
                                    digest(row_id.encode()) + '.json'))


def prepare_undo(store, run_id, row_id, path, original, planted):
    full = store._safe(os.path.join(store.root, path))
    if os.path.islink(full) or os.path.realpath(full) != os.path.abspath(full):
        raise RunError('verify cannot journal a symlinked source path')
    if os.stat(full).st_nlink != 1:
        raise RunError('verify cannot mutate a hardlinked source file; use an independent copy')
    record = {'version': 1, 'run_id': run_id, 'row_id': row_id,
              'path': os.path.relpath(full, store.root),
              'original': base64.b64encode(original).decode(),
              'mode': os.stat(full).st_mode & 0o7777,
              'planted_hash': None if planted is None else digest(planted)}
    atomic_json(store, journal_path(store, run_id, row_id), record)


def guard_original(store, full, original, record):
    store._safe(full)
    if os.path.exists(full):
        metadata = os.stat(full)
        if not stat.S_ISREG(metadata.st_mode) or (record.get('mode') is not None and
                metadata.st_mode & 0o7777 != record['mode']):
            raise RunError(f'recovery conflict at {full}: source type or permissions changed; journal retained')
    current = Path(full).read_bytes() if os.path.exists(full) else None
    if current == original or (current is None and record['planted_hash'] is None) or \
            (current is not None and digest(current) == record['planted_hash']):
        return
    raise RunError(f'recovery conflict at {full}: source changed during verify; journal retained')


def atomic_source_write(store, full, data, journal, record, operation, guard):
    """A killed write changes only an ignored temporary file, never the source bytes."""
    guard()
    temporary = store._safe(str(journal) + '.' + operation)
    mode = record.get('mode')
    if mode is None:
        mode = os.stat(full).st_mode & 0o7777 if os.path.exists(full) else 0o644
    if type(mode) is not int or not 0 <= mode <= 0o7777:
        raise RunError('invalid recovery file mode')
    try:
        with open(temporary, 'wb') as stream:
            stream.write(data)
            os.fchmod(stream.fileno(), mode)
            stream.flush()
            os.fsync(stream.fileno())
        guard()
        os.makedirs(os.path.dirname(full), exist_ok=True)
        os.replace(temporary, full)
        store._sync_dir(os.path.dirname(full))
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def restore_original(store, full, original, journal):
    record = store._read(journal)
    atomic_source_write(store, full, original, journal, record, 'restore',
                        lambda: guard_original(store, full, original, record))


def publication_path(store, run_id):
    return store._safe(os.path.join(store.runs, '.' + store._id(run_id) + '-publication.json'))


def recover_publications(store):
    """Recover the tracked-table link and private staging after interrupted migration."""
    store._safe(store.runs)
    for journal in sorted(Path(store.runs).glob('.*-publication.json')):
        record = store._read(str(journal))
        run_id = record.get('run_id')
        paths = store._paths(run_id)
        staging = store._safe(record['staging'])
        destination = store._safe(record['destination'])
        if record.get('version') != 1 or str(journal) != publication_path(store, run_id) or \
                Path(staging).parent != Path(store.runs) or \
                not Path(staging).name.startswith('.' + run_id + '-') or \
                destination != paths['testcases']:
            raise RunError('invalid pending migration publication')
        published = os.path.exists(paths['run_dir'])
        if not published and os.path.exists(staging):
            manifest = store._read(os.path.join(staging, 'manifest.json'))
            if manifest.get('run_id') != run_id or manifest.get('workspace') != store.root:
                raise RunError('migration staging identity changed; journal retained')
        if published:
            store.inspect(run_id)
            table = Path(paths['run_dir']) / 'migrated-testcases.md'
        else:
            table = Path(destination)

        def validate(path):
            store._safe(path)
            if not os.path.lexists(path):
                raise RunError('migration publication conflict; table missing; journal retained')
            current = os.stat(path, follow_symlinks=False)
            if not stat.S_ISREG(current.st_mode) or \
                    (current.st_dev, current.st_ino) != (record['device'], record['inode']) or \
                    digest(Path(path).read_bytes()) != record['hash']:
                raise RunError('migration publication conflict; preserve the table and reconcile the journal')

        if published:
            # The recovery hardlink is the only copy after destination deletion.
            # Publish it exclusively and sync it before removing recovery state.
            if os.path.lexists(table):
                validate(table)
                if not os.path.lexists(destination):
                    os.makedirs(os.path.dirname(destination), exist_ok=True)
                    try:
                        os.link(table, destination)
                    except FileExistsError:
                        raise RunError('migration publication conflict; destination appeared; journal retained')
                validate(destination)
                store._sync_dir(os.path.dirname(destination))
                table.unlink()
                store._sync_dir(paths['run_dir'])
            else:
                # A kill after recovery-copy removal leaves only the journal.
                validate(destination)
        elif os.path.lexists(table):
            validate(table)
            table.unlink()
            store._sync_dir(os.path.dirname(destination))
        if not published and os.path.exists(staging):
            shutil.rmtree(staging)
        journal.unlink()
        store._sync_dir(store.runs)


def recover(store, engine):
    """Called under the workspace lock, across ALL runs before source is trusted."""
    recover_publications(store)
    for summary in store.list():
        run_id = summary['run_id']
        directory = store._safe(os.path.join(store._paths(run_id)['goalrun_dir'], 'undo'))
        for path in sorted(Path(directory).glob('*.json')):
            record = store._read(str(path))
            if record.get('version') != 1 or record.get('run_id') != run_id:
                raise RunError(f'unsupported recovery journal: {path}')
            rel = record.get('path')
            if not isinstance(rel, str) or os.path.isabs(rel):
                raise RunError(f'invalid recovery path: {path}')
            full = store._safe(os.path.join(store.root, rel))
            if os.path.islink(full) or os.path.realpath(full) != os.path.abspath(full):
                raise RunError(f'recovery target is symlinked: {rel}')
            try:
                original = base64.b64decode(record['original'], validate=True)
            except (KeyError, ValueError, TypeError) as exc:
                raise RunError(f'invalid recovery bytes: {path}') from exc
            guard_original(store, full, original, record)
            current = Path(full).read_bytes() if os.path.exists(full) else None
            if current == original:
                pass  # crash before planting or after restoration
            elif (current is None and record['planted_hash'] is None) or \
                    (current is not None and digest(current) == record['planted_hash']):
                restore_original(store, full, original, str(path))
                print(f'recovered {run_id}/{record["row_id"]}: {rel}', file=sys.stderr)
            else:
                raise RunError(f'recovery conflict at {rel} in {run_id}: source changed after verify; '
                               'reconcile it with the journal before continuing')
            for suffix in ('.restore', '.plant'):
                temporary = store._safe(str(path) + suffix)
                if os.path.exists(temporary):
                    os.unlink(temporary)
            path.unlink()
    # Legacy undo bytes have no planted fingerprint. Never blindly overwrite edits.
    legacy = Path(store.root) / '.testcases/goalrun/undo'
    if legacy.is_dir() and any(legacy.iterdir()):
        raise RunError('legacy pending undo has no guarded fingerprint; reconcile before named runs')


class Tee:
    def __init__(self, terminal, log):
        self.terminal, self.log = terminal, log

    def write(self, value):
        self.terminal.write(value)
        self.log.write(value)
        self.log.flush()
        return len(value)

    def flush(self):
        self.terminal.flush()
        self.log.flush()


class Session:
    def __init__(self, store, run_id, token, engine, args, workspace_fd):
        self.store, self.run_id, self.token, self.engine, self.args = store, run_id, token, engine, args
        self.workspace_fd = workspace_fd
        self.active_row = None
        self.view = store.require(run_id, token)
        self.evidence_dir = store._safe(os.path.join(self.view['paths']['run_dir'], 'evidence'))
        os.makedirs(self.evidence_dir, exist_ok=True)
        self.evidence_id = str(uuid.uuid4())
        self.rows = {}
        self.checks = []
        self.before = fingerprint(store, self.view, engine)

    def record_row(self, row, status, note):
        if note is not None and self.token:
            # a check that echoes its parent command line (ps) would otherwise
            # carry the writer token into the checkpoint and inspect output
            note = note.replace(self.token, '[redacted]')
        self.rows[row.id] = {'status': status, 'note': note,
                             'phase': 'measurement' if status in ('PASS', 'FAIL', 'WAIT') else 'verification'}
        self.publish(self.result())

    def record_check(self, command, exit_code, output, timed_out, row_id=None, phase='measurement',
                     passed=None, note=None):
        if self.token:
            output = output.replace(self.token, '[redacted]')
            if note is not None:
                note = note.replace(self.token, '[redacted]')
        if passed is None:
            passed = exit_code == 0 and not timed_out
        entry = {'command': command, 'exit_code': exit_code, 'timed_out': timed_out, 'output': output,
                 'row_id': row_id, 'phase': phase, 'mutation_row_id': self.active_row,
                 'passed': passed, 'note': note}
        self.checks.append(entry)
        if phase == 'measurement' and row_id is not None and not passed:
            tail = [line.strip() for line in output.splitlines() if line.strip()]
            self.rows[row_id] = {'status': 'FAIL', 'phase': phase,
                                 'note': note if note is not None else (
                                     'timed out' if timed_out else tail[-1][:96] if tail else f'exit {exit_code}')}
        # The checkpoint is the first durable result: any saved command file
        # therefore already has its witnessed failure and proof invalidation.
        self.publish(self.result())
        path = os.path.join(self.evidence_dir, self.evidence_id + f'-check-{len(self.checks)}.json')
        atomic_json(self.store, path, entry)

    def result(self):
        return {'id': self.evidence_id, 'at': time.time(), 'exit_code': None,
                'state': 'unfinished', 'argv': redacted_argv(sys.argv[1:], self.token),
                'fingerprint': self.before, 'input_fingerprint': self.before,
                'inputs_changed': False, 'rows': dict(self.rows),
                'ownership_epoch': self.view['checkpoint']['ownership_epoch'],
                'log': os.path.join(self.evidence_dir, self.evidence_id + '.log'),
                'checks': len(self.checks), 'last_check': self.checks[-1] if self.checks else None,
                'whole_ledger_verified': False}

    def publish(self, result):
        view = self.store.require(self.run_id, self.token)
        cp = view['checkpoint']
        previous = cp.get('last_evidence') or {}
        counted = set(previous.get('counted_failures', [])) if previous.get('id') == self.evidence_id else set()
        failing = {row_id for row_id, outcome in self.rows.items()
                   if outcome['status'] not in ('PASS', 'VERIFIED', 'WAIT')}
        for row_id in failing - counted:
            cp['failures'][row_id] = cp['failures'].get(row_id, 0) + 1
        result['counted_failures'] = sorted(counted | failing)
        proof = latest_proof(cp)
        if result['whole_ledger_verified']:
            cp['last_proof'] = dict(result)
        elif proof is not None:
            cp['last_proof'] = dict(proof)
            if failing or result['inputs_changed'] or (result['exit_code'] not in (None, 0) and self.checks):
                cp['last_proof']['invalidated_by'] = self.evidence_id
        cp['last_evidence'] = result
        cp['generation'] += 1
        self.store._save(view, cp)

    def prepare(self, row_id, path, original, planted):
        self.active_row = row_id
        prepare_undo(self.store, self.run_id, row_id, path, original, planted)

    def plant(self, full, planted):
        path = journal_path(self.store, self.run_id, self.active_row)
        record = self.store._read(path)
        original = base64.b64decode(record['original'], validate=True)

        def guard():
            self.store._safe(full)
            metadata = os.stat(full)
            if not stat.S_ISREG(metadata.st_mode) or metadata.st_mode & 0o7777 != record['mode'] or \
                    Path(full).read_bytes() != original:
                raise RunError('source changed before planting; journal retained')

        atomic_source_write(self.store, full, planted, path, record, 'plant', guard)

    def delete(self, full):
        path = journal_path(self.store, self.run_id, self.active_row)
        record = self.store._read(path)
        original = base64.b64decode(record['original'], validate=True)
        self.store._safe(full)
        if Path(full).read_bytes() != original or (os.stat(full).st_mode & 0o7777) != record['mode']:
            raise RunError('source changed before deletion; journal retained')
        os.unlink(full)
        self.store._sync_dir(os.path.dirname(full))

    def restore(self, full, original):
        path = journal_path(self.store, self.run_id, self.active_row)
        restore_original(self.store, full, original, path)

    def restored(self, row_id):
        # Atomic compare-and-restore completed before clearing the journal.
        path = journal_path(self.store, self.run_id, row_id)
        if os.path.exists(path):
            os.unlink(path)
        self.active_row = None

    def finish(self, code, log_path):
        view = self.store.require(self.run_id, self.token)
        after = fingerprint(self.store, view, self.engine)
        result = self.result()
        result.update({'exit_code': code, 'state': 'completed', 'fingerprint': after,
                       'inputs_changed': self.before != after, 'log': log_path,
                       'whole_ledger_verified': code == 0 and self.args.verify == '' and self.before == after})
        self.publish(result)
        atomic_json(self.store, os.path.join(self.evidence_dir, self.evidence_id + '.json'), result)


@contextmanager
def bind(engine, view, session):
    paths = view['paths']
    names = ('GOAL_DIR', 'LEDGER', 'SIGNOFF', 'BASELINE', 'UNDO_DIR', 'SESSION')
    old = {name: getattr(engine, name) for name in names}
    engine.GOAL_DIR = paths['goalrun_dir']
    engine.LEDGER = os.path.join(engine.GOAL_DIR, 'ledger.tsv')
    engine.SIGNOFF = os.path.join(engine.GOAL_DIR, 'signoff.tsv')
    engine.BASELINE = os.path.join(engine.GOAL_DIR, 'baseline.json')
    engine.UNDO_DIR = os.path.join(engine.GOAL_DIR, 'undo')
    engine.SESSION = session
    try:
        yield
    finally:
        for name, value in old.items():
            setattr(engine, name, value)


def require_baseline(view, engine):
    path = os.path.join(view['paths']['goalrun_dir'], 'baseline.json')
    baseline = engine.read_baseline(path=path)
    if not isinstance(baseline, dict) or not isinstance(baseline.get('files'), dict):
        raise RunError('run baseline missing or invalid; restore the original baseline, never retake it')


def named_engine(engine, args):
    store = Store()
    if not args.run:
        if args.token:
            raise RunError('--token requires --run')
        with workspace_lock(engine):
            if store.list():
                raise RunError('named runs exist; select --run explicitly (list/inspect to find unfinished work)')
            return engine.run(args, locked=True)
    if args.ledger is not None or args.requirements is not None:
        raise RunError('named runs bind ledger and requirements together; do not override their paths')
    if args.baseline is not None or args.reset:
        raise RunError('named baseline is taken once by init; resume never retakes or resets it')
    with store.lock(args.run), workspace_lock(engine) as lock:
        view = store.require(args.run, args.token)
        recover(store, engine)
        require_baseline(view, engine)
        ledger = store._safe(os.path.join(view['paths']['goalrun_dir'], 'ledger.tsv'))
        store._safe(os.path.join(view['paths']['goalrun_dir'], engine.WAIVER_BINDINGS))
        if os.path.exists(ledger):
            engine.bind_waivers(ledger)
        session = Session(store, args.run, args.token, engine, args, lock.fileno())
        log_path = os.path.join(session.evidence_dir, session.evidence_id + '.log')
        with bind(engine, view, session), os.fdopen(
                os.open(log_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600),
                'w', encoding='utf-8') as log:
            args.ledger = engine.LEDGER
            if args.lint_ledger:
                args.requirements = os.path.join(engine.GOAL_DIR, 'reqs.txt')
            code = 2
            with redirect_stdout(Tee(sys.stdout, log)), redirect_stderr(Tee(sys.stderr, log)):
                try:
                    if args.verify == '':
                        rows = engine.load(engine.LEDGER)
                        reqs = engine.read_requirements(os.path.join(engine.GOAL_DIR, 'reqs.txt'))
                        problems = engine.lint(rows, engine.load_signatures(),
                                               has_baseline=True, waived=engine.authorized_waivers(engine.LEDGER, rows),
                                               requirements=reqs)
                        if problems:
                            for problem in problems:
                                print(problem)
                            print('NOT DONE — ledger coverage or design failed lint')
                            code = 1
                            return code
                    code = engine.run(args, locked=True)
                    if args.verify == '' and code == 0 and session.before != fingerprint(store, view, engine):
                        print('NOT DONE — inputs changed during verification; rerun on stable inputs')
                        code = 1
                    return code
                except KeyboardInterrupt:
                    code = 130
                    raise
                finally:
                    session.finish(code, log_path)


def initialize_run(store, engine, args):
    """Stage the complete payload before making the run visible to other controllers."""
    destination = store._paths(args.run_id)['testcases']
    cases = Path(store.root) / 'testcases.md'
    migrating_cases = args.action == 'migrate' and cases.exists()
    if migrating_cases and os.path.lexists(destination):
        raise RunError('migration testcase destination already exists; reconcile its permanent IDs first')

    def populate(paths):
        if args.action == 'init':
            engine.take_baseline(path=os.path.join(paths['goalrun_dir'], 'baseline.json'))
            return
        legacy = Path(store.root) / '.testcases/goalrun'
        for name in ('ledger.tsv', 'reqs.txt', 'baseline.json', 'signoff.tsv', engine.WAIVER_BINDINGS):
            if name == engine.WAIVER_BINDINGS:
                store._safe(legacy / name)
                if (legacy / name).is_symlink():
                    raise RunError(f'waiver binding path is symlinked: {legacy / name}')
            if (legacy / name).exists():
                shutil.copy2(legacy / name, Path(paths['goalrun_dir']) / name)
        for name, dest in (('docs-review', 'docs_review_dir'), ('testcase', 'testcase_dir')):
            source = Path(store.root) / '.testcases' / name
            if source.exists():
                shutil.copytree(source, paths[dest], dirs_exist_ok=True)
        if migrating_cases:
            staged_table = Path(paths['run_dir']) / 'migrated-testcases.md'
            shutil.copy2(cases, staged_table)
            store._safe(destination)
            os.makedirs(os.path.dirname(destination), exist_ok=True)
            identity = staged_table.stat()
            atomic_json(store, publication_path(store, args.run_id), {
                'version': 1, 'run_id': args.run_id, 'staging': paths['run_dir'],
                'destination': destination, 'device': identity.st_dev, 'inode': identity.st_ino,
                'hash': digest(staged_table.read_bytes()),
            })
            # Record ownership before linking, so SIGKILL cleanup is recoverable.
            os.link(staged_table, destination)
            store._sync_dir(os.path.dirname(destination))

    try:
        store.create(args.run_id, args.goal, args.spec, populate=populate)
    except BaseException:
        recover_publications(store)
        raise
    recover_publications(store)


def lifecycle(engine, argv):
    parser = argparse.ArgumentParser(description='Persistent goalrun lifecycle (JSON output)')
    parser.add_argument('action', choices=ACTIONS)
    parser.add_argument('run_id', nargs='?')
    parser.add_argument('--goal')
    parser.add_argument('--spec', default='')
    parser.add_argument('--owner')
    parser.add_argument('--token')
    parser.add_argument('--expected-generation', type=int)
    parser.add_argument('--phase')
    parser.add_argument('--next', dest='next_action')
    parser.add_argument('--note', default='')
    parser.add_argument('--failure')
    a = parser.parse_args(argv)
    store = Store()
    if a.action == 'list':
        if a.run_id:
            raise RunError('list does not take a run id')
        print(json.dumps(store.list(), indent=2))
        return 0
    if not a.run_id:
        raise RunError('select a run id explicitly')
    if a.action == 'inspect':
        print(json.dumps(evidence_view(store, store.inspect(a.run_id), engine), indent=2))
        return 0
    with store.lock(a.run_id), workspace_lock(engine):
        recover(store, engine)
        if a.action in ('init', 'migrate'):
            if a.action == 'migrate':
                legacy = Path(store.root) / '.testcases/goalrun'
                if not (legacy / 'baseline.json').is_file():
                    raise RunError('migration needs the existing legacy baseline; never take a new one mid-work')
            initialize_run(store, engine, a)
            result = store.inspect(a.run_id)
        elif a.action == 'resume':
            existing = store.inspect(a.run_id)
            require_baseline(existing, engine)
            evidence_view(store, existing, engine)  # validate all inputs before revoking an owner
            result = store.resume(a.run_id, a.owner, a.expected_generation)
        elif a.action == 'release':
            result = store.release(a.run_id, a.token, a.note)
        else:
            result = store.checkpoint(a.run_id, a.token, a.phase, a.next_action, a.note, a.failure)
        result = evidence_view(store, result, engine)
        if a.action == 'resume':
            result['token'] = store.inspect(a.run_id)['checkpoint']['token']
        print(json.dumps(result, indent=2))
    return 0
